### ISSUE TITLE
CSV, PDF and other session report to be export as webservice

### ISSUE THREAD

**Issue by antolinos** [ispyb/ISPyB#135]
We need to make the reports accessible via WebServices
Related to issue:
https://github.com/ispyb/EXI/issues/259

![image](https://user-images.githubusercontent.com/2901169/27436757-884980da-5760-11e7-86f6-b75caec256bd.png)

**Comment by delageniere** [comment]
A report already exists : see ispyb-ws/ispyb/ws/rest/DataCollectionRestWebService/getDataCollectionReportBySessionId

It is a simpler version of the report of ispyb-ui
If we want to have exactly the same reports, then it would be better to rewrite them because they are using complex objects created especially for the display in ispyb-ui which may be no more used when switched to EXI.
@Stephanie : could you please describe the reports you would like ?

**Comment by antolinos** [comment]
@delageniere 

Which are the valid values of parameter:  @PathParam("reportType") String reportType?

Thanks,
A.

**Comment by delageniere** [comment]
Good question because at first it was meant to be really a type of report and a real string but I used it later for testing purposes and reducing the number of lines, so now it should be an integer representing the nb of rows of the exported datacollection.
I can take this issue to rename this parameter + add some cast tests to improve. the code.
What do you think ?

**Comment by antolinos** [comment]
It sounds good to me. In the meantime, can I use it? If so, which value/s
should be passed?

**Comment by delageniere** [comment]
Ok then I take it, and you can use it, and pass a huge integer if you want to see all line, like 100, or less if you want to restrict the report, but use only integer.

**Comment by antolinos** [comment]
Then reportType=10000 and a parameter rename is expected

Thanks

**Comment by delageniere** [comment]
Comment by David Von Stetten : 
Do you think it would be possible to make them interactive by embedding
links to the corresponding EXI pages, such that clicking on a data
collection in the PDF opens the page of this data collection in a browser?

**Comment by delageniere** [comment]
@antolinos : the nbRows has been moved as QueryParam, so is not any more in the url
and the new analysis report is available (some modifications to extract the correct Best autoproc is still needed). 
May be useless if another way of generating pdf/rtf is found, extracting directly from js on client side.
