### ISSUE TITLE
Null pointer exception in ToolsForEMDataCollection.addMovie 110

### ISSUE THREAD

**Issue by delageniere** [ispyb/ISPyB#266]
Inn the logs, there are a lot of errors due to a null pointer exception when adding a movie at ToolsForEMDataCollection.addMovie line 110.

**Comment by antolinos** [comment]
Hi @delageniere,

I would not say that it is a bug. startTime could be null or not in the right format so we are catching the exception. 
I don't see the problem.

https://github.com/ispyb/ISPyB/blob/7cbd6e34d24d85f6227df9589a4b59d171756606/ispyb-ws/src/main/java/ispyb/ws/soap/em/ToolsForEMDataCollection.java#L110

As you can see in the code this is because we are catching if an error happens during the coversion of dates from the beamline.

```java
               Date startTime = Calendar.getInstance().getTime();
		try{
			SimpleDateFormat dt = new SimpleDateFormat("yyyyy-mm-dd hh:mm:ss"); 
			startTime = dt.parse(stringStartTime); 
		}
		catch(Exception exp){
			exp.printStackTrace();
			log.error("Error addMovie: {}", exp.getCause());
}
```

Cheers,
A.

**Comment by delageniere** [comment]
Yes, you're right, it's ok. I was digging in the logs on Friday and saw a lot of these errors but had no time to check.
