### ISSUE TITLE
Work on user portal dependencies

### ISSUE THREAD

**Issue by delageniere** [ispyb/ISPyB#379]
Following questions from @jlmuir  :

_What is dependencies/ispyb-WSclient-userportal-gen-1.4.jar?  What uses
it?  Why is it a dependency of ISPyB (when it has "client" in its name,
and ISPyB is a server, not a client)?_

It seems a good idea first to rename the jar, as it is not a client but it contains the generated classes and files describing the user portal objects used to retrieve data from the user portal both at ESRF and EMBL HH. 
This jar can be generated using the "ispyb-WSClient-gen" project  which calls the User Portal WS to generate these classes from the WSDL.

And later on, it could be also a good idea to get rid of this dependency, and to have an intermediate format of data coming from user portals (jsons for example).

**Comment by jlmuir** [comment]
Thank you, @delageniere!

@delageniere wrote:
> This jar can be generated using the "ispyb-WSClient-gen" project which calls the User Portal WS to generate these classes from the WSDL.

I can't find the "ispyb-WSClient-gen" project. Is it publicly available and I just missed it, or is it an internal project? I'm OK if it's internal, but if it's publicly available somewhere, I'd take a look at it.

**Comment by delageniere** [comment]
The project belongs to my repositories on github, you can find it on : 
https://github.com/delageniere/ispyb-WSclient-gen

May be I should add it to ISPyB repositories if it can be useful to others ?

**Comment by jlmuir** [comment]
@delageniere wrote:
> The project belongs to my repositories on github, you can find it on :
https://github.com/delageniere/ispyb-WSclient-gen

There it is!  Thank you!

> May be I should add it to ISPyB repositories if it can be useful to others ?

I don't know enough about ISPyB to offer an opinion on that.  Since I'm just trying to understand things, it was a help to be able to see how your `ispyb-WSclient-gen` project worked, but the main thing was just understanding what it was, and then I was thinking it would be nice to be able to look at it if it was publicly available; once you told me where it was, that was good enough for me.  Thanks again!

**Comment by delageniere** [comment]
Yes, the pom.xml has been changed, release 5.13.1 contains the new name of the jar.
