### ISSUE TITLE
SOAP, getDescriptionByExperimentId: empty return value

### ISSUE THREAD

**Issue by dfranke76** [ispyb/ISPyB#53]
On the EMBL-HH test installation I query the list of available experiments for a proposal and get:

"[{\"experimentId\":3771,\"experimentType\":\"TEMPLATE\",
\"dataCollectionDoneCount\":0,\"measurementDoneCount\":0,
\"measurementAveragedCount\":0,\"specimenCount\":6,\"creationDate\":\"Mar 
14, 2017 10:12:00 AM\",\"name\":\"\",\"measurementCount\":15,
\"dataCollectionCount\":5,\"proposalId\":4,\"macromolecules\":\"BSA\",
\"comments\":\"\"}]"

Now, feeding the above experimentId into the same kind of code as 
everywhere else ...

  QtSoapMessage request;
  request.setMethod("getDescriptionByExperimentId",
                    "http://ispyb.ejb3.webservices.biosaxs");
  request.addMethodArgument("experimentId", "", id);

I get an error. Which, on closer inspection, indicates that the return value is invalid, i.e. empty. The WSDL only defines this one argument in this exact spelling, nothing extra and all other calls work without known problems. If I modify the above and add, say, proposal code and number (as with many other calls), I get an "internal server error" instead. Any idea?

Thanks.

**Comment by antolinos** [comment]
@dfranke76 

An error was produced because of duplicated alias in a SQL query. It happened since we changed the version of Hibernate (long time ago...)
I have modified the query by creating a new view in the DB and then I have made a pull request.

At the same time I have added this into ispyb-client
https://github.com/ispyb/ispyb-client/blob/master/python/biosaxs/sampleChanger/GenericSampleChangerPipeline.py
