### ISSUE TITLE
Problem searching for samples by containerId

### ISSUE THREAD

**Issue by sergiogf93** [ispyb/ISPyB#60]
When the following url is called:

**/{token}/proposal/{proposal}/mx/sample/containerid/{containerId}/list**

The samples with protein acronym gp120 are not found. If you search with:

**/{token}/proposal/{proposal}/shipping/{containerId}/dewar/{containerId}/puck/{containerId}/get**

They are found.

This problem only happens when logged in the ESRF database: when logged in the ESRF TEST database it works fine.

**Comment by sergiogf93** [comment]
The same happens with samples with protein acronym INS and FAE

**Comment by delageniere** [comment]
There is an inconsistency between the proposal number in Shipping and in Protein so it can not be displayed with the 1st url.
Test with :
 SELECT BLSample.*, Shipping.proposalId, Protein.proposalId FROM `BLSample`, Crystal, Protein, Shipping, Dewar, Container WHERE BLSample.crystalId = Crystal.crystalId and Crystal.proteinId = Protein.proteinId and acronym like "gp120" and Shipping.proposalId = 1170 and
 Shipping.shippingId = Dewar.shippingId and Dewar.dewarId = Container.dewarId and Container.containerId = BLSample.containerId;

This should not happen: the shipment could not be created with samples from protein attached to another proposal.

Have to investigate further if only due to tests or if this is a real bug

**Comment by delageniere** [comment]
Found some answers : 
Some are due to BAG continuation and transfer of protein from one account to the other.
Some are linked to tests, but still not completely explained.
See:
SELECT 
        distinct BLSample.recordTimeStamp, concat(`Proposal`.`proposalCode`, `Proposal`.`proposalNumber`) as ship ,concat(`proposal2`.`proposalCode`, `proposal2`.`proposalNumber`) as prot
    FROM
        (((((((`BLSample`
        LEFT JOIN `Crystal` ON ((`Crystal`.`crystalId` = `BLSample`.`crystalId`)))
        LEFT JOIN `Protein` ON ((`Protein`.`proteinId` = `Crystal`.`proteinId`)))
        LEFT JOIN `Container` ON ((`BLSample`.`containerId` = `Container`.`containerId`)))
        LEFT JOIN `Dewar` ON ((`Dewar`.`dewarId` = `Container`.`dewarId`)))
        LEFT JOIN `Shipping` ON ((`Dewar`.`shippingId` = `Shipping`.`shippingId`)))
        LEFT JOIN `Proposal` ON ((`Proposal`.`proposalId` = `Shipping`.`proposalId`)))
        LEFT JOIN `Proposal` as proposal2 ON ((`proposal2`.`proposalId` = `Protein`.`proposalId`)))
        where Shipping.proposalId != Protein.proposalId  order by recordTimeStamp desc
